[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "CalSciPy"
version = "0.1.6"
description = "A collection"
readme = "README.md"
requires-python = ">=3.7, <4"
license = {file = "LICENSE"}
keywords = ["CalSciPy", "Calcium Imaging"]
authors = [
  {name = "Darik A. O'Neil"}
]
maintainers = [
    {name = "Darik A. O'Neil"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

dependencies = [
    "imageio",
    "imageio[ffmpeg]",
    "matplotlib",
    "numba",
    "numpy",
    "pandas",
    "pillow",
    "PPVD",
    "prettytable",
    "seaborn",
    "scipy",
    "scikit-image",
    "tifffile",
    "tqdm"
]
[project.urls]
documentation = "https://calscipy.readthedocs.io/en/latest/?badge=latest"
repository = "https://github.com/darikoneil/CalSciPy"


[project.optional-dependencies]

development = [
    "build",
    "coverage[toml]",
    "coveralls",
    "flake8",
    "pytest",
    "pytest-datafiles",
    "pytest-progress",
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx_autodoc_typehints",
    "twine"
]

gpu = [
    "cupy"
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "-s",
    "--color=yes",
    "-vv",
    "--diff-width=120"
]
testpaths = "tests"
console_output_style = "progress"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::FutureWarning"
]

[tool.coverage.run]
branch = true
command_line = "-m pytest"

[tool.coverage.report]
fail_under = 75

[tool.coverage.json]
pretty_print = true

[tool.coverage.lcov]
output = "C:/coverage.lcov"

